[bumpver]
current_version = "0.11.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[bumpver.file_patterns]
# "setup.py" = ["{version}", "{pep440_version}"]
"setup.py" = ['version = "{version}"']
# "README.md" = ["{version}", "{pep440_version}"]
"README.md" = ['Latest version: {version}']
"bumpver.toml" = ['current_version = "{version}"']
"pyproject.toml" = ['version = "{version}"']
"wmutils/__init__.py" = ['version = "{version}"']
